# Generated by Django 5.0 on 2025-10-11 11:51

import Store.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('CustomerContact', models.CharField(max_length=20)),
                ('CustomerAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='Product.jpg', upload_to=Store.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='Product.jpg', upload_to=Store.models.user_directory_path)),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customerdetails')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.productdetails')),
            ],
        ),
    ]
