# Generated by Django 5.0 on 2025-10-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='SessionOrderID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
