# Generated by Django 5.0 on 2025-10-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_orderdetails_sessionorderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='Description',
            field=models.TextField(blank=True, help_text='Product description', null=True),
        ),
    ]
